@startuml

hide class
hide circle
hide methods
hide empty members
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

class BackofficeOperator {
    email
}

class Customer {
    id
    name
}

class AirTransportCompany {
    name
    iataCode
    icaoCode
}

class AirControlArea {
    code
    name
}

class CustomerCollaborator {
    email
    name
    position
    status
}

class CollaboratorStatus {
    active
    disabled
}

class CollaboratorList {
    activeCollaborators
}

Customer <|-- AirTransportCompany
Customer <|-- AirControlArea

BackofficeOperator "1" -- "*" CollaboratorList : requests >
CollaboratorList "1" o-- "*" CustomerCollaborator : contains >
Customer "1" -- "*" CustomerCollaborator : has >
CustomerCollaborator "1" -- "1" CollaboratorStatus : has >

@enduml