@startuml

hide class
hide circle
hide methods
hide empty members
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

class AirTransportCompanyCollaborator {
    email
    name
    position
}

class AirTransportCompany {
    name
    iataCode
    icaoCode
}

class Fleet {
    aircraft
}

class Aircraft {
    registrationNumber
    registeredCountry
    operationalStatus
    referenceDate
}

class AircraftAge {
    years
    months
}

class AgeCriteria {
    minimumAge
    maximumAge
    sortingOrder
}

class AircraftModel {
    modelName
}

class AircraftEngineModel {
    modelName
}

class AircraftConfiguration {
    aircraftModel
    engineModel
}

class CabinConfiguration {
    totalSeats
}

class FleetByAgeListing {
    ageCriteria
}

AirTransportCompanyCollaborator "*" -- "1" AirTransportCompany : belongs to >
AirTransportCompany "1" -- "1" Fleet : has >
Fleet "1" o-- "*" Aircraft : contains >
Aircraft "*" -- "1" AirTransportCompany : owned by >
Aircraft "1" -- "1" AircraftAge : has calculated >
Aircraft "1" -- "1" AircraftConfiguration : has >
AircraftConfiguration "*" -- "1" AircraftModel : uses >
AircraftConfiguration "*" -- "1" AircraftEngineModel : uses >
Aircraft "1" -- "1" CabinConfiguration : has >
FleetByAgeListing "1" -- "1" AgeCriteria : uses >
FleetByAgeListing "1" o-- "*" Aircraft : returns >

@enduml