@startuml

hide class
hide circle
hide methods
hide empty members
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

class User {
    email
    name
    phoneNumber
    status
}

class UserStatus {
    enabled
    disabled
}

class Role {
    name
}

class UserList {
    users
}

class Authorization {
    requiredPermission
}

UserList "1" o-- "*" User : contains >
User "1" -- "1" UserStatus : has >
User "1" -- "1..*" Role : has >
Authorization "1" -- "*" UserList : protects access to >

@enduml